# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy -compat=1.17
builds:
  - id: "rpi-monitor"
    main: "main.go"
    binary: "monitor"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
#      - amd64
      - arm
#      - arm64
    goarm:
      - 6
      - 7
    ldflags:
#      - -s -w
      - -s -w -X "main.Version={{.Env.APP_VERSION}}" -X "main.GitBranch={{.Env.GIT_BRANCH}}" -X "main.GitCommit={{.Env.GIT_COMMIT}}" -X "main.BuildTime={{.Env.BUILD_TIME}}"

archives:
   - files:
      - src: 'monitor.yaml.example'
        strip_parent: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge'